[package]
name = "speiceio_pyo3"
version = "0.1.0"
authors = ["Bradlee Speice <bradlee@speice.io>"]
edition = "2018"

[profile.release]
# Use opt-level 2 to make the code comparable to C++, which also compiles at -O2
opt-level = 2

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = "*"
