# Manually-maintained type definitions. Because `setuptools-rust` places the compiled Rust lib
# inside the package directory,

def fibonacci_gil(n: int) -> int: ...
def fibonacci_nogil(n: int) -> int: ...
